### ISSUE TITLE
Feat: add executor parameter to test job

### ISSUE THREAD

**Issue by abriemme** [CircleCI-Public/python-orb#107]
## Describe Request:
We should add a `executor` parameter to the `test` job in order to use another `executor`, allowing multiple docker images (like adding postgres image to the python ones).
## Examples:
Adding a `executor` parameter:
```
version: 2.1

orbs:
    python: circleci/python@2.1.1

executors:
    python_with_postgres:
        docker:
            - image: cimg/python:3.10
              environment:
                - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
            - image: cimg/postgres
              environment:
                - POSTGRES_DB=postgres
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=postgres
workflows:
  test:
    jobs:
      - python/test:
          executor: python_with_postgres
```
## Supporting Documentation Links:
[The maven-orb already have this parameter ](https://github.com/CircleCI-Public/maven-orb/blob/master/src/jobs/test.yml#L9-L12)
