### ISSUE TITLE
Restoring cache error: possibly related to the wrong check for symbolic link

### ISSUE THREAD

**Issue by gnoejnooh** [CircleCI-Public/python-orb#110]
## What happened:

Restoring cache step from `python/install-packages` is showing error. I was able to find related [PR](https://github.com/CircleCI-Public/python-orb/pull/89#issuecomment-1034019711) for 2.0.1 and applied suggested changes but it did not help and the error still persists.

The error message from the failed Restoring cache step is as follows:
```
error computing cache key: template: cacheKey:1:32: executing "cacheKey" at <checksum "/tmp/cci_pycache/lockfile">: error calling checksum: open /tmp/cci_pycache/lockfile: no such file or directory
```

## Expected behavior:
Restore cache without an error.

## Additional Information:
Current config file setup:
```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  python: circleci/python@2.1.1

executors:
  python:
    parameters:
      tag:
        type: string
        default: "3.10"
    docker:
      - image: cimg/python:<< parameters.tag >>

jobs:
  pytest:
    executor:
      name: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          cache-version: v2
          args: --with=dev,type_check --sync
...
```
