### ISSUE TITLE
Feature request: Support for `uv` package installer

### ISSUE THREAD

**Issue by paulmelero** [CircleCI-Public/python-orb#120]
## Describe Request:

Official support for https://github.com/astral-sh/uv for faster installs.

> `uv` is an extremely fast Python package resolver and installer, designed as a drop-in replacement for `pip`, `pip-tools` (`pip-compile` and `pip-sync`), and `virtualenv`.

It has some [limitations](https://github.com/astral-sh/uv#limitations), so I don't know if it would be that _easy_ to add it as a "drop-in replacement", depending on the `pip` features you use currently.

## Examples:

```
version: '2.1'
orbs:
  python: circleci/python@<...>
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
```

## Supporting Documentation Links:

- https://github.com/astral-sh/uv
