### ISSUE TITLE
Simple installation fails on cache creation

### ISSUE THREAD

**Issue by kevin-kortum-trustedshops** [CircleCI-Public/python-orb#130]
## Orb version:
3.1.0

## What happened:

Consider the following snippet
```yaml
parameters:
  version:
    type: string
    default: ""
    description: "pre-commit version e.g. '4.2.0'. If empty installing latest version."

steps:
  - when:
      condition: << parameters.version >>
      steps:
        - python/install-packages:
            pkg-manager: auto
            args: "pre-commit==<< parameters.version >>"
  - unless:
      condition: << parameters.version >>
      steps:
        - python/install-packages:
            pkg-manager: auto
            args: "pre-commit"
  - run:
      name: Show installed pre-commit version
      command: pre-commit --version
```

After the `Save python version` step a `Reset cache` step is run erroring
```
error computing cache key: template: cacheKey:1:70: executing "cacheKey" at <checksum "./.cci_pycache/lockfile">: error calling checksum: open /home/circleci/project/.cci_pycache/lockfile: no such file or directory
```

The orb then continues with minimal information about what has been done so far. Then again on the `Save cache` step

```
Error computing cache key: template: cacheKey:1:70: executing "cacheKey" at <checksum "./.cci_pycache/lockfile">: error calling checksum: open /home/circleci/project/.cci_pycache/lockfile: no such file or directory
``` 

## Expected behavior:

The orb installs the package and i can use it in my pipeline.

## Additional Information:

I want to use the python orb simply to make a binary/command available to the pipeline. There is no source code or anything relying on python, so no requirements.txt is provided. The orb uses the `cimg/node-lts` image to run.
