### ISSUE TITLE
[QUESTION] How do you create a config.yml for windows and Linux?

### ISSUE THREAD

**Issue by achapkowski** [CircleCI-Public/python-orb#59]
## Describe Request:
I am trying to update some legacy configs that only worked in Linux, but our package works on Windows.  Is there a simple example showing how to run a python build/test workflow on multiple OS?

## Examples:

Looking for one :)

## Supporting Documentation Links:

Couldn't find any.

**Comment by achapkowski** [comment]
Current Config:

```
version: 2.1

orbs: 
  python: circleci/python@0.3.2

jobs: 
  build-and-test: 
    docker:
      - image: circleci/python:3.7.9
    environment: PYTHONPATH=./src
    executor: python/default
    steps: 
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test
  lint-and-coverage: 
    docker:
      - image: circleci/python:3.7.9
    environment: PYTHONPATH=./src
    executor: python/default
    steps: 
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - 
        run: 
          command: |
              coverage run
              coverage report
          name: Coverage

workflows: 
  main: 
    jobs: 
      - build-and-test
      - lint-and-coverage

```
