### ISSUE TITLE
pytest PYTHONPATH to include CIRCLE_WORKING_DIRECTORY 

### ISSUE THREAD

**Issue by tjian** [CircleCI-Public/python-orb#60]
## Orb version:
1.2.1

## What happened:
```yml
steps:
    - run:
        command: |
            export PYTHONPATH=$PWD:$PYTHONPATH
            python -m unittest
        name: Run tests with global python env
        working_directory: <<parameters.app-dir>>
```

When I passed in `app-dir`, PYTHONPATH should include `app-dir`

i.e.
```yml
export PYTHONPATH=$CIRCLE_WORKING_DIRECTORY:$PWD:$PYTHONPATH
```

My work-around is to `setup` to export PYTHONPATH:
```yml
      - python/test:
          setup:
            - run:
                name: "set up PYTHONPATH"
                command: echo 'export PYTHONPATH="/home/circleci/project/foo"' >> $BASH_ENV
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest
          version: '3.7'
          app-dir: '~/project/foo'
```

## Expected behavior:
It should run the test suite and shouldn't error out with `ModuleNotFoundError:`
