### ISSUE TITLE
Python 3.9.0 not supported

### ISSUE THREAD

**Issue by sondrelg** [CircleCI-Public/python-orb#62]
## Orb version:

1.2.1

## What happened:

This is my job

```yaml

orbs:
  python: circleci/python@1.2.1
jobs:
  linting:
    executor: python/default
    steps:
      - checkout
      # Install dependencies
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-flake8.txt
          args: black==19.10.b0 safety
      # Run linters
      - run:
          name: Run flake8
          when: always
          command: flake8 --show-source --statistics
      - run:
          name: Run black
          when: always
          command: black --check .
      - run:
          name: Safety check
          when: always
          command: bash -c 'poetry export -f requirements.txt --without-hashes | safety check --stdin'
```

Which works well when my `.python-version` is 3.8.5, but fails when I upgrade to 3.9.0.

It fails during the package-install-step

![image](https://user-images.githubusercontent.com/25310870/99967001-833c2280-2d97-11eb-9ca9-81d674aa6f43.png)

## Expected behavior:

Python 3.9.0 should run like other versions.

**Comment by dsayling** [comment]
Hi there! The `default` executor for the python orb uses python 3.8.
https://circleci.com/developer/orbs/orb/circleci/python#executors-default


To use a 3.9 image simply update the executor in your config like this:
```
jobs:
  linting:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
```
