### ISSUE TITLE
Python 3.9.0 stopped working on orb 1.2.1

### ISSUE THREAD

**Issue by sondrelg** [CircleCI-Public/python-orb#65]
## Orb version:

1.2.1 and 1.3.0

## What happened:

We've been running linting using this orb for a few weeks on Python 3.9.0, and somewhere between 6 hours go and 1 hour ago, something broke.

![image](https://user-images.githubusercontent.com/25310870/101882546-f2828680-3b8d-11eb-9b46-7804557992a2.png)

## Additional Information:

This is our setup

```yaml
orbs:
  python: circleci/python@1.3.0
jobs:
  linting:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-flake8.txt
          args: black==20.8b1 safety
    ...
```

Our circleci configuration is unchanged.
