### ISSUE TITLE
install-packages does not respect the existing working_directory

### ISSUE THREAD

**Issue by sestrella** [CircleCI-Public/python-orb#72]
## What happened:

I have a python project inside a `subdirectory`, the path to the `subdirectory` is set as the `working_directory` at the job level, my configuration file looks similar to this:

```yml
build:
  executor: python/default
  working_directory: ~/project/subdirectory
  steps:
    - checkout:
        path: ~/project
    - python/install-packages:
        pkg-manager: pip
```

However, it looks like `install-packages` command is not able to find the `requirements.txt` file in the context of the `working_directory`:

![image](https://user-images.githubusercontent.com/2049686/112344001-a9b09280-8c91-11eb-8cda-7afb9f67d80c.png)

I found a quick around, setting `app-dir` to the same path specified in the `working_directory` solved the problem, however, it feels a little bit redundant

```yml
build:
  executor: python/default
  working_directory: ~/project/subdirectory
  steps:
    - checkout:
        path: ~/project
    - python/install-packages:
        pkg-manager: pip
        app-dir: ~/project/subdirectory # Workaround
```

## Expected behavior:

`install-packages` should operate in the context of the existing `working_directory`.
