### ISSUE TITLE
Allow list of files to checksum for the purposes of caching

### ISSUE THREAD

**Issue by the21st** [CircleCI-Public/python-orb#78]
## Describe Request:

Allow choosing multiple files to checksum for the purposes of caching.

## Examples:

We have a python repo with multiple requirements files:
`requirements_base.txt` - the base requirements file
`requirements_test.txt` - this one starts with `-r requirements_base.txt` and adds some testing-specific packages

I want to specify both of these files in my `python/test` job so that whenever any of them changes, the cache is invalidated.

**Comment by gmemstr** [comment]
The only solution I can come up with for this is concatenating the list of files together then using that file's checksum for the cache. I don't super love that approach though. While I can see the utility in this addition, my current leaning is to encourage the community to show backing of this addition before investing time into adding it. If someone else opens a PR to fill this gap, I'll happily review it :)

**Comment by glebsts** [comment]
I stepped into that story with multiple `requirements` files, checked sources... Looks like you can do
```
workflows:
  main:
    jobs:
      - python/test:
          pip-dependency-file:
            dev-requirements.txt -r requirements.txt
```

and it indeed installs both files, because it just [concats](https://github.com/CircleCI-Public/python-orb/blob/0b14cd9764556eec54fe4442d57eab337a7c923c/src/commands/install-packages.yml#L142) `pip install -r <<parameters.pip-dependency-file>>`, but yeah, **cache restore/save is broken**, as `checksum` step tries to calculate checksum on file `<< parameters.app-dir >>/<<parameters.pip-dependency-file>>` a la `error calling checksum: open /home/circleci/project/dev-requirements.txt -r requirements.txt`

If you don't care about cache, this can be the way.

I checked orb sources, but unfortunately parameter is string, and in general **array parameters are not supported**, as it is hard to build for-loop into yaml (and other reasons discussed [here](https://discuss.circleci.com/t/list-parameter-type/26705/6))

I ended up with _commented timestamp inside `requirements.txt` that I bump if I need to add/update some dependency_ (in any of requirement files) (could be auto-updated by IDE [for example](https://github.com/shiyanhui/FileHeader)), and adding secondary requirement file(s) as `args` parameter, so that:
```
workflows:
  main:
    jobs:
      - python/test:
          args: -r dev-requirements.txt
```
On timestamp change checksum is changed, so cache is being not-restored + saved.

`args` parameter is being [added to the end](https://github.com/CircleCI-Public/python-orb/blob/0b14cd9764556eec54fe4442d57eab337a7c923c/src/commands/install-packages.yml#L142) of `pip install` command

Quite a workaround, but still no need to define whole job manually a la
```
jobs:
  pip-install-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys: ....
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
      - python/install-packages:
          pip-dependency-file: requirements.txt
      - save_cache:
          keys: ....
      - run:
          command:  ...
```

Hope it will help somebody.

Really need array parameter support in orbs :(
