### ISSUE TITLE
Poetry dependencies cache failing after moving from docker cimg/python to machine ubuntu executor

### ISSUE THREAD

**Issue by carlosjgp** [CircleCI-Public/python-orb#93]
## Orb version:

```
orbs:
  python: circleci/python@2.0.0
```

## What happened:

"Restoring cache" fails with
```
error computing cache key: template: cacheKey:1:32: executing "cacheKey" at <checksum "/tmp/cci_pycache/lockfile">: error calling checksum: open /tmp/cci_pycache/lockfile: no such file or directory
```

"Saving cache" fails with
```
Error computing cache key: template: cacheKey:1:32: executing "cacheKey" at <checksum "/tmp/cci_pycache/lockfile">: error calling checksum: open /tmp/cci_pycache/lockfile: no such file or directory
```

![image](https://user-images.githubusercontent.com/1277613/157214600-363e8caf-5abe-48b2-b2b1-bd2c34af4c43.png)

### Full job spec

```
orbs:
  python: circleci/python@2.0.0
  aws-cli: circleci/aws-cli@2.0.6

aliases:
  - &python-image
    resource_class: small
    docker:
      - image: cimg/python:3.10

  - &machine-image
    resource_class: small
    machine:
      image: ubuntu-2004:202111-02

  test-with-testcontainers:
    # Machine type for testcontainers
    <<: [*machine-image, *testing-job-params]
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - pyenv-versions-{{ checksum "<< parameters.path>>/.python-version" }}
      - run:
          name: "Set Python Version"
          command: |
            # Use the same Python version as the Docker image and local developers using pyenv
            pyenv install $(cat << parameters.path>>/.python-version) --skip-existing
            pyenv global $(cat << parameters.path>>/.python-version)
            # install the same dependencies as on the Docker image
            pip install --no-cache-dir -r << parameters.path>>/docker/requirements.txt
      - save_cache:
          key: pyenv-versions-{{ checksum "<< parameters.path>>/.python-version" }}
          paths:
            - /opt/circleci/.pyenv/versions
      - aws-cli/install
      - python/install-packages:
          pkg-manager: poetry
          app-dir: << parameters.path>>
      - run: cd << parameters.path>> && make test
      # Get codecov results on CircleCI tabs
      - store_test_results:
          path: << parameters.path>>/test-results
      - store_artifacts:
          path: << parameters.path>>/htmlcov
```

## Expected behaviour:

Cache should be stored and restored successfully
